version: "3.9"

services:
  api:
    build:
      context: ../
    container_name: web_api
    volumes:
        - ../secrets.json:/app/secrets.json
    #   - ../django-local-efs:/var/www/django-local-efs
    ports:
      - 7000:7000

  nginx:
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - api
  
  app:
    build:
      context: ../app
      dockerfile: Dockerfile.app
    container_name: web_app
    ports:
      - 3000:3000
    depends_on:
      - api